services:
  api:
    build: ./api
    env_file:
      - .env
    ports:
      - 8002:8002
    volumes:
      - ./api/src:/app/src
      - ./api/residence.sqlite:/app/residence.sqlite
    healthcheck:
      test: 'curl --fail --request GET --url ''http://localhost:8002/'' || exit 1'
      interval: 1s
      timeout: 2s
      retries: 100

  front:
    build: ./front
    env_file:
      - .env
    volumes:
      - ./front/src:/app/src
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --request GET --url 'http://localhost:5173/' || exit 1"
      interval: 1s
      timeout: 2s
      retries: 100

  redis:
    image: redis

  apigateway:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      api:
        condition: service_healthy
      front:
        condition: service_healthy
    ports:
      - "8080:80"