services:
  api:
    build: ./api
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
    volumes:
      - ./api/residence.sqlite:/app/residence.sqlite

  front:
    build: 
      context: ./front
      dockerfile: Dockerfile.prod
      args:
        VITE_BACKEND_URL: ${BACKEND_URL}
        VITE_MAIL_SERVICE_ID: ${MAIL_SERVICE_ID}
        VITE_MAIL_TEMPLATE_ID: ${MAIL_TEMPLATE_ID}
        VITE_MAIL_PUBLIC_KEY: ${MAIL_PUBLIC_KEY}
        VITE_RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
        VITE_STATUS: ${STATUS}

  redis:
    image: redis

  apigateway:
    image: nginx
    volumes:
      - ./nginx_logs:/var/log/nginx
      - ./prod.nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"