services:
  api:
    build: ./api
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
    volumes:
      - ./api/residence.sqlite:/app/residence.sqlite
    healthcheck:
      test: "curl --fail --request GET --url 'http://localhost:8002/api' || exit 1"
      interval: 1s
      timeout: 2s
      retries: 20

  front:
    build: 
      context: ./front
      dockerfile: Dockerfile.prod
      args:
        VITE_BACKEND_URL: ${BACKEND_URL}
        VITE_STATUS: ${STATUS}
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --request GET --url 'http://localhost:80/' || exit 1"
      interval: 1s
      timeout: 2s
      retries: 20

  redis:
    image: redis

  apigateway:
    image: nginx
    volumes:
      - ./prod.nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      api:
        condition: service_healthy
      front:
        condition: service_healthy
    ports:
      - "8080:80"