FROM node:20-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG VITE_BACKEND_URL
ARG VITE_MAIL_SERVICE_ID
ARG VITE_MAIL_TEMPLATE_ID
ARG VITE_MAIL_PUBLIC_KEY
ARG VITE_RECAPTCHA_SITE_KEY
ARG VITE_STATUS
RUN npm run build

FROM nginx:alpine
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]