POST http://localhost:8002/contact-form
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doee",
  "email": "john@doe.com",
  "phone": "0606060606",
  "message": "Hello, I am interested in your product!"
}

###

GET http://localhost:8002/contact-forms